
variables:
  VERSION: 1.0.$CI_PIPELINE_ID

stages:
  - build

build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn versions:set -DnewVersion=$VERSION
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
      - target/jacoco-ut/*
