
stages:
  - testapp
  - build
  - publish

test:
  stage: testapp
  image: maven:3-jdk-8
  script:
    - mvn testapp

build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

publish:
  stage: publish
  image: debian:jessie
  script:
    - echo "Uh oh it's not done yet..."
  only:
    - master
