
stages:
  - test
  - build
  - publish

test:
  stage: test
  image: maven:3-jdk-8
  script:
    - mvn test

build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

publish:
  stage: publish
  image: debian:jessie
  script:
    - echo "Uh oh it's not done yet..."
    - exit 1
